config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'image_crop#index'
  resources :image_crop
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :profile_pic, ImageUploader
  has_one :picture_edit_detail, foreign_key: 'picture_id'
  validates :profile_pic, presence: true
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :scale_x, :scale_y, :rotate

  after_update :crop_avatar

  def crop_avatar
    self.profile_pic.recreate_versions! if crop_x.present? && self.profile_pic.present?
  end
end

app/models/picture_edit_detail.rb
class PictureEditDetail < ApplicationRecord
  belongs_to :picture
end

app/controllers/application_controller.rb
# frozen_string_literal: false

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/cropping_concern.rb
module CroppingConcern

	def crop_and_save
		pict = Picture.create(picture_params)
		if pict && crop_x.present?
			PictureEditDetail.create(picture_id: pict.id, scale_x: scale_x, scale_y: scale_y, rotate: rotate, pic_x: crop_x, pic_y: crop_y, pic_w: crop_w, pic_h: crop_h)
			flash[:notice] = 'Image successfully created!!!'
		else
			flash[:error] = 'Something went wrong.'
		end
	end

	def update_picture
		if picture.present?
      if crop_x.present?
        picture.picture_edit_detail.update_attributes(scale_x: scale_x, scale_y: scale_y, rotate: rotate, pic_x: crop_x, pic_y: crop_y, pic_w: crop_w, pic_h: crop_h)
      end
      flash[:notice] = 'Image successfully updated!!!'
    else
      flash[:error] = 'Something went wrong.'
    end
	end

	def picture
		Picture.find_by(id: params[:id])
	end

	private

	def picture_params
    params.require(:picture).permit(:crop_x, :scale_x, :scale_y, :rotate, :crop_y, :crop_w, :crop_h, :profile_pic)
  end

  def crop_x
  	picture_params.dig(:crop_x)
  end

  def crop_y
  	picture_params.dig(:crop_y)
  end

  def crop_w
  	picture_params.dig(:crop_w)
  end

  def crop_h
  	picture_params.dig(:crop_h)
  end

  def scale_x
  	picture_params.dig(:scale_x)
  end

  def scale_y
  	picture_params.dig(:scale_y)
  end

  def rotate
  	picture_params.dig(:rotate)
  end

  def profile_pic
  	picture_params.dig(:profile_pic)
  end

end

app/controllers/image_crop_controller.rb
class ImageCropController < ApplicationController
  include CroppingConcern

  def index
    @pictures = Picture.all.paginate(page: params[:page], per_page: 10)
  end

  def create
    crop_and_save
    redirect_to root_path
  end

  def show
    @picture = Picture.find_by(id: params[:id])
    unless @picture.present?
      return redirect_to root_path, notice: 'No image found !'
    end
  end

  def update
    update_picture
    redirect_to root_path
  end

  def destroy
    if picture.destroy
      flash[:notice] = 'Image successfully destroyed!!!'
    else
      flash[:error] = 'Something went wrong !'
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_crop_helper.rb
# frozen_string_literal: false

module ImageCropHelper
end

app/views/image_crop/index.html.erb
<% unless @pictures.present? %>
  <h1 style="text-align: center;">There is no image !!!</h1>
<% end %>

<% if @pictures.present? %>
  <h1 style="text-align: center;">Images</h1>
  <table>
    <tr>
      <th>Name</th>
      <th>Action</th>
    </tr>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.profile_pic_url.split('/')[-1] %></td>
        <td><%= link_to "View", image_crop_path(id: picture), class: 'btn btn-success' %></td>
      </tr>
    <% end %>
  </table><br>
  <div class = "digg_pagination" >
    <%= will_paginate @pictures %>
  </div>
<% end %>

<%= render partial: 'shared/profile_pic_upload_modal', :locals => { :picture => Picture.new, :url => image_crop_index_path, :request => :post} %>

<%= link_to 'Add New Image', 'javascript:void(0);', data: {toggle: "modal", target: "#profile_pic_upload"}, class: 'btn btn-primary' %>

app/views/image_crop/show.html.erb
<div class="new_img_shape_wrapper" style="text-align: center;">
  <%= image_tag(@picture.try(:profile_pic).url(:thumb), id: "profile_pic_preview", class:"pro_pic_prev img_sze") %>
  <span class="new_shape_bg">
    <?xml version="1.0" encoding="utf-8"?>
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
      width="348.6px" height="300.7px" viewBox="0 0 348.6 300.7" style="enable-background:new 0 0 348.6 300.7;" xml:space="preserve"
      >
      <style type="text/css">
        .st0{fill:#C41E1E;}
      </style>
      <path class="st0" d="M18.1,102.6c-0.1,0.4-3.5,12-2.1,26.7c1,10.3,1.5,21.2,4.5,31.5c3,10.3,21.8,44,26.3,52.8
        c6.9,13.3,14.2,23.8,16.8,28c16.6,27.1,41.2,43.9,52.6,50c42.1,12.9,100.2,7.2,148.3-21c43.9-24.7,68.4-57.6,68.7-100.6
        c-0.9-36.5-12.6-62.5-31.7-81.4c-24-24.7-51.2-40.1-81.3-47.7c-26.2-9.3-54.4-11-84-7.7c-23,4.2-46.2,11.4-69.7,20.7
        c-13.5,7.3-23.9,15.6-34.8,28.5c15.3-21.8,33.7-39,58.8-55.8c18.2-10.9,36.7-19.1,55.3-23.7c14.8-2.8,30.6-3.5,47.3,0
        c23.5,8.4,49.2,24.6,77,48c28.2,20.9,52.9,44.5,69.7,74.3c9.4,25.2,11.4,48.9,2,70c-7.6,17.6-16.4,30-28.8,42.6
        c-5.7,6.4-22.1,20.5-42.5,32.8c-13,7.8-29.3,14.7-40.1,18.7c-10.3,3.5-29.6,9.3-52.4,10.6c-22,1.3-47.4-1.8-53.3-3.3
        c-32.9-5.3-58.4-22-83-40c-17.5-16.9-30.6-37.6-38-63.7c-4.4-17.8-3.6-36.2,0-55C6.6,126,10.4,116.3,18.1,102.6z"/>
    </svg>
  </span>
</div>
<%= render partial: 'shared/profile_pic_upload_modal', :locals => { :picture => @picture, :url => image_crop_path(id: @picture), :request => :patch} %>
<div style="text-align: center;">
  <%= link_to 'Back', root_path, class: 'btn btn-primary' %>
  <%= link_to "Edit", 'javascript:void(0);', data: {toggle: "modal", target: "#profile_pic_upload"}, class: 'btn btn-success' %>
  <%= link_to "Destroy", image_crop_path(id: @picture), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %></td>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_without_login_header.html.erb
<nav  class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "ImageCropping", root_path, class: 'navbar-brand' %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageCropping</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/without_login_header'%>
    <%= render partial: '/layouts/flash' unless flash.empty? %>
    <section class='login_wrapper'>
      <div class= 'container'>
        <%= yield %>
      </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_profile_pic_upload_modal.html.erb
<div class="page_wrapper wdth100">
  <div class="add_new_section_mdl_main">
    <div class="modal fade" id="profile_pic_upload" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
      <div class="modal-dialog modal-lg delete_section_modal img_modal_upload" role="document">
        <div class="modal-content">
          <div class="delete_modl_wrap">
            <div class="modal-header adm_del_mod">
              <div class="verify_modal_head">
                <h2 class="modal-title profile_photo_heading" style="text-align: inherit;">Add a photo</h2>
              </div>
            </div>
            <div class="modal-body">
              <div class="modal_container">
                <%= form_for(:picture, url: url, method: request, html:{ class: 'user_login_form'}) do |f|%>
                  <% if picture.present? && picture.profile_pic.present? %>
                    <div class="img_shape_wrapper modal_img_shape main_image_center" id="prf_upld">
                      <%= image_tag(picture.profile_pic_url(:thumb), id: "profile_pic_preview") %>
                      <span class="shape_bg shape_center">
                        <svg version="1.1" id="Layer_2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="304.1px" height="253.8px" viewBox="0 0 304.1 253.8" style="enable-background:new 0 0 304.1 253.8;" xml:space="preserve">
                          <path d="M86.2,253.4c-14.3-9.6-55.4-79.6-60.3-97c-11.7-33.5-7.5-59.7,12.3-78.7c19.9-19.6,44.8-30.6,72.7-36
                            c37-5.6,70.6-2,101.3,9.3c23.9,9.3,44.4,22.8,60.3,41.7c9.5,9.2,17.1,22.9,23,40.7c3.4,12.2,3.2,37.5,3.2,37.5s6.9-20.1,4.2-40.5
                            c-2-15-12.7-32.8-16.7-38.3c-5.1-6.3-25.4-27.3-46.8-44.7c-24.5-19.8-50.2-35.7-50.2-35.7c-7.1-4.6-26.9-12.8-47.8-11.3
                            C119,1.9,95.2,13.5,84.1,20.2C72.7,27,55.8,39.1,43.6,51.4c-6.1,6.2-14.9,16.9-21.3,27C14.8,90,9.9,100.7,9.9,100.7
                            c-3.5,7.9-12.8,34.5-8.2,59.5c2.4,12.8,9.3,35.8,24.5,53c7.1,8,13.2,14.4,20.8,20c11.9,8.7,24.2,14.5,24.2,14.5L86.2,253.4z"></path>
                        </svg>
                      </span>
                    </div>
                  <% else %>
                    <div class="pirkx_user_login_img login_non_img_bg" id="prf_upld">
                      DP
                    </div>
                  <% end %>
                <%= f.hidden_field "pro_pic", value:"#{picture.profile_pic_url if picture.present? && picture.profile_pic.present?}"%>
                <%= f.hidden_field "crop_x", value:"#{picture.try(:picture_edit_detail).try(:pic_x) if picture.present? && picture.picture_edit_detail.present?}"%>
                <%= f.hidden_field "crop_y", value:"#{picture.try(:picture_edit_detail).try(:pic_y) if picture.present? && picture.picture_edit_detail.present?}"%>
                <%= f.hidden_field "crop_w", value:"#{picture.try(:picture_edit_detail).try(:pic_w) if picture.present? && picture.picture_edit_detail.present?}"%>
                <%= f.hidden_field "crop_h", value:"#{picture.try(:picture_edit_detail).try(:pic_h) if picture.present? && picture.picture_edit_detail.present?}"%>
                <%= f.hidden_field "scale_y", value:"#{picture.try(:picture_edit_detail).try(:scale_y).present? ? picture.picture_edit_detail.try(:scale_y) : 1 }"%>
                <%= f.hidden_field "scale_x", value:"#{picture.try(:picture_edit_detail).try(:scale_x).present? ? picture.try(:picture_edit_detail).try(:scale_x) : 1 }"%>
                <%= f.hidden_field "rotate", value:"#{picture.try(:picture_edit_detail).try(:rotate).present? ? picture.try(:picture_edit_detail).try(:rotate) : 0 }"%>
                <input type="hidden" id="old_zoom" value="0">
                <div class="zm_btn">
                  <%= button_tag "Zoom In", type: "button", class: "default_btn aqua_btn", id: "zoom_in", style: "display: none;"%>
                  <%= button_tag "Zoom Out", type: "button", class: "default_btn aqua_btn", id: "zoom_out", style: "display: none;"%>
                </div>
                <div class="modal_btn add_pics prfl_btn_margin">
                  <div class="upld_btn_wrap profilee_pop_up_btn pos_rel profile_image_upldr" >
                    <span class=""></span>
                    <% if true %>
                      <a href="javascript:void(0);" class="default_btn" style="background: transparent;border:1px solid #3cbfae;color: #151515;margin-right: 21px;" id="remove_btn"> Upload a photo
                        <%= f.file_field :profile_pic, accept: "image/png, image/jpeg, image/jpg, image/gif", style: "cursor: pointer;"%>
                      </a>
                    <% end %>
                  </div>
                  <% if picture.present? && picture.profile_pic.present? %>
                    <%= button_tag "Edit", type:"button", class: 'default_btn aqua_btn', id: 'edit_pic' %>
                  <% end %>
                </div>
                <div class="modal_btn add_pics prfl_btn_margin">
                  <div class="upld_btn_wrap profilee_pop_up_btn pos_rel profile_image_upldr" style="display: none; margin-right: 9px;" id="submit_profile">
                    <%= button_tag "Save", class: 'default_btn orange_btn' %>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "image_crop/image_crop.js" %>
<%= javascript_include_tag "crop.js" %>